version: "3.5"
volumes:
  portainer_data:

  jellyfin-cache:
    driver: local
  jellyfin-config:
    driver: local
services:
  nginx:
    image: nginx:alpine
    depends_on: 
      - jellyfin
    ports:
      - 8085:80
    networks: 
      minharede:
          ipv4_address: 10.11.10.12
          aliases: 
              - nginx
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks: 
      minharede:
          ipv4_address: 10.11.10.13
          aliases: 
              - jellyfin
    volumes:
      - /home/victor/Documents/Programas/jellyfin/config:/config
      - /home/victor/Documents/Programas/jellyfin/cache:/cache
      - /home/victor/Documents/Programas/jellyfin/media:/media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8096:8096
networks:
  minharede:
      ipam: 
          driver: default
          config:
              - subnet: 10.11.10.0/24